// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BrandKitsColumns holds the columns for the "brand_kits" table.
	BrandKitsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "prompt", Type: field.TypeString},
		{Name: "concept", Type: field.TypeJSON},
		{Name: "results", Type: field.TypeJSON, Nullable: true},
		{Name: "trust_score", Type: field.TypeFloat64, Default: 0},
		{Name: "fingerprint", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_kits", Type: field.TypeInt, Nullable: true},
	}
	// BrandKitsTable holds the schema information for the "brand_kits" table.
	BrandKitsTable = &schema.Table{
		Name:       "brand_kits",
		Columns:    BrandKitsColumns,
		PrimaryKey: []*schema.Column{BrandKitsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "brand_kits_users_kits",
				Columns:    []*schema.Column{BrandKitsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// OtpsColumns holds the columns for the "otps" table.
	OtpsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString},
		{Name: "code", Type: field.TypeString},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// OtpsTable holds the schema information for the "otps" table.
	OtpsTable = &schema.Table{
		Name:       "otps",
		Columns:    OtpsColumns,
		PrimaryKey: []*schema.Column{OtpsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "otp_email",
				Unique:  false,
				Columns: []*schema.Column{OtpsColumns[1]},
			},
		},
	}
	// ProvidersColumns holds the columns for the "providers" table.
	ProvidersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "provider_name", Type: field.TypeString},
		{Name: "provider_account_id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_providers", Type: field.TypeInt},
	}
	// ProvidersTable holds the schema information for the "providers" table.
	ProvidersTable = &schema.Table{
		Name:       "providers",
		Columns:    ProvidersColumns,
		PrimaryKey: []*schema.Column{ProvidersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "providers_users_providers",
				Columns:    []*schema.Column{ProvidersColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "provider_provider_name_provider_account_id",
				Unique:  true,
				Columns: []*schema.Column{ProvidersColumns[1], ProvidersColumns[2]},
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "session_email",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[2]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BrandKitsTable,
		OtpsTable,
		ProvidersTable,
		SessionsTable,
		UsersTable,
	}
)

func init() {
	BrandKitsTable.ForeignKeys[0].RefTable = UsersTable
	OtpsTable.Annotation = &entsql.Annotation{
		Table: "otps",
	}
	ProvidersTable.ForeignKeys[0].RefTable = UsersTable
}
