// Code generated by ent, DO NOT EDIT.

package provider

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/trnahnh/katana-id/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldID, id))
}

// ProviderName applies equality check predicate on the "provider_name" field. It's identical to ProviderNameEQ.
func ProviderName(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldProviderName, v))
}

// ProviderAccountID applies equality check predicate on the "provider_account_id" field. It's identical to ProviderAccountIDEQ.
func ProviderAccountID(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldProviderAccountID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldCreatedAt, v))
}

// ProviderNameEQ applies the EQ predicate on the "provider_name" field.
func ProviderNameEQ(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldProviderName, v))
}

// ProviderNameNEQ applies the NEQ predicate on the "provider_name" field.
func ProviderNameNEQ(v string) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldProviderName, v))
}

// ProviderNameIn applies the In predicate on the "provider_name" field.
func ProviderNameIn(vs ...string) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldProviderName, vs...))
}

// ProviderNameNotIn applies the NotIn predicate on the "provider_name" field.
func ProviderNameNotIn(vs ...string) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldProviderName, vs...))
}

// ProviderNameGT applies the GT predicate on the "provider_name" field.
func ProviderNameGT(v string) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldProviderName, v))
}

// ProviderNameGTE applies the GTE predicate on the "provider_name" field.
func ProviderNameGTE(v string) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldProviderName, v))
}

// ProviderNameLT applies the LT predicate on the "provider_name" field.
func ProviderNameLT(v string) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldProviderName, v))
}

// ProviderNameLTE applies the LTE predicate on the "provider_name" field.
func ProviderNameLTE(v string) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldProviderName, v))
}

// ProviderNameContains applies the Contains predicate on the "provider_name" field.
func ProviderNameContains(v string) predicate.Provider {
	return predicate.Provider(sql.FieldContains(FieldProviderName, v))
}

// ProviderNameHasPrefix applies the HasPrefix predicate on the "provider_name" field.
func ProviderNameHasPrefix(v string) predicate.Provider {
	return predicate.Provider(sql.FieldHasPrefix(FieldProviderName, v))
}

// ProviderNameHasSuffix applies the HasSuffix predicate on the "provider_name" field.
func ProviderNameHasSuffix(v string) predicate.Provider {
	return predicate.Provider(sql.FieldHasSuffix(FieldProviderName, v))
}

// ProviderNameEqualFold applies the EqualFold predicate on the "provider_name" field.
func ProviderNameEqualFold(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEqualFold(FieldProviderName, v))
}

// ProviderNameContainsFold applies the ContainsFold predicate on the "provider_name" field.
func ProviderNameContainsFold(v string) predicate.Provider {
	return predicate.Provider(sql.FieldContainsFold(FieldProviderName, v))
}

// ProviderAccountIDEQ applies the EQ predicate on the "provider_account_id" field.
func ProviderAccountIDEQ(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldProviderAccountID, v))
}

// ProviderAccountIDNEQ applies the NEQ predicate on the "provider_account_id" field.
func ProviderAccountIDNEQ(v string) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldProviderAccountID, v))
}

// ProviderAccountIDIn applies the In predicate on the "provider_account_id" field.
func ProviderAccountIDIn(vs ...string) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldProviderAccountID, vs...))
}

// ProviderAccountIDNotIn applies the NotIn predicate on the "provider_account_id" field.
func ProviderAccountIDNotIn(vs ...string) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldProviderAccountID, vs...))
}

// ProviderAccountIDGT applies the GT predicate on the "provider_account_id" field.
func ProviderAccountIDGT(v string) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldProviderAccountID, v))
}

// ProviderAccountIDGTE applies the GTE predicate on the "provider_account_id" field.
func ProviderAccountIDGTE(v string) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldProviderAccountID, v))
}

// ProviderAccountIDLT applies the LT predicate on the "provider_account_id" field.
func ProviderAccountIDLT(v string) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldProviderAccountID, v))
}

// ProviderAccountIDLTE applies the LTE predicate on the "provider_account_id" field.
func ProviderAccountIDLTE(v string) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldProviderAccountID, v))
}

// ProviderAccountIDContains applies the Contains predicate on the "provider_account_id" field.
func ProviderAccountIDContains(v string) predicate.Provider {
	return predicate.Provider(sql.FieldContains(FieldProviderAccountID, v))
}

// ProviderAccountIDHasPrefix applies the HasPrefix predicate on the "provider_account_id" field.
func ProviderAccountIDHasPrefix(v string) predicate.Provider {
	return predicate.Provider(sql.FieldHasPrefix(FieldProviderAccountID, v))
}

// ProviderAccountIDHasSuffix applies the HasSuffix predicate on the "provider_account_id" field.
func ProviderAccountIDHasSuffix(v string) predicate.Provider {
	return predicate.Provider(sql.FieldHasSuffix(FieldProviderAccountID, v))
}

// ProviderAccountIDEqualFold applies the EqualFold predicate on the "provider_account_id" field.
func ProviderAccountIDEqualFold(v string) predicate.Provider {
	return predicate.Provider(sql.FieldEqualFold(FieldProviderAccountID, v))
}

// ProviderAccountIDContainsFold applies the ContainsFold predicate on the "provider_account_id" field.
func ProviderAccountIDContainsFold(v string) predicate.Provider {
	return predicate.Provider(sql.FieldContainsFold(FieldProviderAccountID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Provider {
	return predicate.Provider(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Provider {
	return predicate.Provider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Provider {
	return predicate.Provider(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Provider) predicate.Provider {
	return predicate.Provider(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Provider) predicate.Provider {
	return predicate.Provider(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Provider) predicate.Provider {
	return predicate.Provider(sql.NotPredicates(p))
}
