// Code generated by ent, DO NOT EDIT.

package brandkit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/trnahnh/katana-id/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldLTE(FieldID, id))
}

// Prompt applies equality check predicate on the "prompt" field. It's identical to PromptEQ.
func Prompt(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldEQ(FieldPrompt, v))
}

// TrustScore applies equality check predicate on the "trust_score" field. It's identical to TrustScoreEQ.
func TrustScore(v float64) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldEQ(FieldTrustScore, v))
}

// Fingerprint applies equality check predicate on the "fingerprint" field. It's identical to FingerprintEQ.
func Fingerprint(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldEQ(FieldFingerprint, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldEQ(FieldCreatedAt, v))
}

// PromptEQ applies the EQ predicate on the "prompt" field.
func PromptEQ(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldEQ(FieldPrompt, v))
}

// PromptNEQ applies the NEQ predicate on the "prompt" field.
func PromptNEQ(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldNEQ(FieldPrompt, v))
}

// PromptIn applies the In predicate on the "prompt" field.
func PromptIn(vs ...string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldIn(FieldPrompt, vs...))
}

// PromptNotIn applies the NotIn predicate on the "prompt" field.
func PromptNotIn(vs ...string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldNotIn(FieldPrompt, vs...))
}

// PromptGT applies the GT predicate on the "prompt" field.
func PromptGT(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldGT(FieldPrompt, v))
}

// PromptGTE applies the GTE predicate on the "prompt" field.
func PromptGTE(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldGTE(FieldPrompt, v))
}

// PromptLT applies the LT predicate on the "prompt" field.
func PromptLT(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldLT(FieldPrompt, v))
}

// PromptLTE applies the LTE predicate on the "prompt" field.
func PromptLTE(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldLTE(FieldPrompt, v))
}

// PromptContains applies the Contains predicate on the "prompt" field.
func PromptContains(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldContains(FieldPrompt, v))
}

// PromptHasPrefix applies the HasPrefix predicate on the "prompt" field.
func PromptHasPrefix(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldHasPrefix(FieldPrompt, v))
}

// PromptHasSuffix applies the HasSuffix predicate on the "prompt" field.
func PromptHasSuffix(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldHasSuffix(FieldPrompt, v))
}

// PromptEqualFold applies the EqualFold predicate on the "prompt" field.
func PromptEqualFold(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldEqualFold(FieldPrompt, v))
}

// PromptContainsFold applies the ContainsFold predicate on the "prompt" field.
func PromptContainsFold(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldContainsFold(FieldPrompt, v))
}

// ResultsIsNil applies the IsNil predicate on the "results" field.
func ResultsIsNil() predicate.BrandKit {
	return predicate.BrandKit(sql.FieldIsNull(FieldResults))
}

// ResultsNotNil applies the NotNil predicate on the "results" field.
func ResultsNotNil() predicate.BrandKit {
	return predicate.BrandKit(sql.FieldNotNull(FieldResults))
}

// TrustScoreEQ applies the EQ predicate on the "trust_score" field.
func TrustScoreEQ(v float64) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldEQ(FieldTrustScore, v))
}

// TrustScoreNEQ applies the NEQ predicate on the "trust_score" field.
func TrustScoreNEQ(v float64) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldNEQ(FieldTrustScore, v))
}

// TrustScoreIn applies the In predicate on the "trust_score" field.
func TrustScoreIn(vs ...float64) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldIn(FieldTrustScore, vs...))
}

// TrustScoreNotIn applies the NotIn predicate on the "trust_score" field.
func TrustScoreNotIn(vs ...float64) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldNotIn(FieldTrustScore, vs...))
}

// TrustScoreGT applies the GT predicate on the "trust_score" field.
func TrustScoreGT(v float64) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldGT(FieldTrustScore, v))
}

// TrustScoreGTE applies the GTE predicate on the "trust_score" field.
func TrustScoreGTE(v float64) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldGTE(FieldTrustScore, v))
}

// TrustScoreLT applies the LT predicate on the "trust_score" field.
func TrustScoreLT(v float64) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldLT(FieldTrustScore, v))
}

// TrustScoreLTE applies the LTE predicate on the "trust_score" field.
func TrustScoreLTE(v float64) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldLTE(FieldTrustScore, v))
}

// FingerprintEQ applies the EQ predicate on the "fingerprint" field.
func FingerprintEQ(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldEQ(FieldFingerprint, v))
}

// FingerprintNEQ applies the NEQ predicate on the "fingerprint" field.
func FingerprintNEQ(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldNEQ(FieldFingerprint, v))
}

// FingerprintIn applies the In predicate on the "fingerprint" field.
func FingerprintIn(vs ...string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldIn(FieldFingerprint, vs...))
}

// FingerprintNotIn applies the NotIn predicate on the "fingerprint" field.
func FingerprintNotIn(vs ...string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldNotIn(FieldFingerprint, vs...))
}

// FingerprintGT applies the GT predicate on the "fingerprint" field.
func FingerprintGT(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldGT(FieldFingerprint, v))
}

// FingerprintGTE applies the GTE predicate on the "fingerprint" field.
func FingerprintGTE(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldGTE(FieldFingerprint, v))
}

// FingerprintLT applies the LT predicate on the "fingerprint" field.
func FingerprintLT(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldLT(FieldFingerprint, v))
}

// FingerprintLTE applies the LTE predicate on the "fingerprint" field.
func FingerprintLTE(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldLTE(FieldFingerprint, v))
}

// FingerprintContains applies the Contains predicate on the "fingerprint" field.
func FingerprintContains(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldContains(FieldFingerprint, v))
}

// FingerprintHasPrefix applies the HasPrefix predicate on the "fingerprint" field.
func FingerprintHasPrefix(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldHasPrefix(FieldFingerprint, v))
}

// FingerprintHasSuffix applies the HasSuffix predicate on the "fingerprint" field.
func FingerprintHasSuffix(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldHasSuffix(FieldFingerprint, v))
}

// FingerprintIsNil applies the IsNil predicate on the "fingerprint" field.
func FingerprintIsNil() predicate.BrandKit {
	return predicate.BrandKit(sql.FieldIsNull(FieldFingerprint))
}

// FingerprintNotNil applies the NotNil predicate on the "fingerprint" field.
func FingerprintNotNil() predicate.BrandKit {
	return predicate.BrandKit(sql.FieldNotNull(FieldFingerprint))
}

// FingerprintEqualFold applies the EqualFold predicate on the "fingerprint" field.
func FingerprintEqualFold(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldEqualFold(FieldFingerprint, v))
}

// FingerprintContainsFold applies the ContainsFold predicate on the "fingerprint" field.
func FingerprintContainsFold(v string) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldContainsFold(FieldFingerprint, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BrandKit {
	return predicate.BrandKit(sql.FieldLTE(FieldCreatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.BrandKit {
	return predicate.BrandKit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.BrandKit {
	return predicate.BrandKit(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BrandKit) predicate.BrandKit {
	return predicate.BrandKit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BrandKit) predicate.BrandKit {
	return predicate.BrandKit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BrandKit) predicate.BrandKit {
	return predicate.BrandKit(sql.NotPredicates(p))
}
