package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"

	"github.com/trnahnh/katana-id/internal/model"
)

// BrandKit is one generated brand: the source prompt, the Gemini-generated
// concept, the aggregated availability results across every platform, and the
// trust score computed for the request that produced it.
type BrandKit struct {
	ent.Schema
}

func (BrandKit) Fields() []ent.Field {
	return []ent.Field{
		field.String("prompt").NotEmpty(),
		field.JSON("concept", model.BrandConcept{}),
		field.JSON("results", []model.Availability{}).Optional(),
		field.Float("trust_score").Default(0),
		field.String("fingerprint").Optional(),
		field.Time("created_at").Default(time.Now).Immutable(),
	}
}

func (BrandKit) Edges() []ent.Edge {
	return []ent.Edge{
		// Kits may be generated by an authenticated user; the edge is optional so
		// anonymous generations can still be persisted for the results stream.
		edge.From("owner", User.Type).Ref("kits").Unique(),
	}
}
