ALTER TABLE sessions ALTER COLUMN token DROP DEFAULT;

ALTER TABLE otps ALTER COLUMN id DROP DEFAULT;

ALTER TABLE providers ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE providers ALTER COLUMN id DROP DEFAULT;

ALTER TABLE users ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
