// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/trnahnh/katana-id/internal/db/ent/brandkit"
	"github.com/trnahnh/katana-id/internal/db/ent/predicate"
	"github.com/trnahnh/katana-id/internal/db/ent/user"
	"github.com/trnahnh/katana-id/internal/model"
)

// BrandKitUpdate is the builder for updating BrandKit entities.
type BrandKitUpdate struct {
	config
	hooks    []Hook
	mutation *BrandKitMutation
}

// Where appends a list predicates to the BrandKitUpdate builder.
func (_u *BrandKitUpdate) Where(ps ...predicate.BrandKit) *BrandKitUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *BrandKitUpdate) SetPrompt(v string) *BrandKitUpdate {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *BrandKitUpdate) SetNillablePrompt(v *string) *BrandKitUpdate {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetConcept sets the "concept" field.
func (_u *BrandKitUpdate) SetConcept(v model.BrandConcept) *BrandKitUpdate {
	_u.mutation.SetConcept(v)
	return _u
}

// SetNillableConcept sets the "concept" field if the given value is not nil.
func (_u *BrandKitUpdate) SetNillableConcept(v *model.BrandConcept) *BrandKitUpdate {
	if v != nil {
		_u.SetConcept(*v)
	}
	return _u
}

// SetResults sets the "results" field.
func (_u *BrandKitUpdate) SetResults(v []model.Availability) *BrandKitUpdate {
	_u.mutation.SetResults(v)
	return _u
}

// AppendResults appends value to the "results" field.
func (_u *BrandKitUpdate) AppendResults(v []model.Availability) *BrandKitUpdate {
	_u.mutation.AppendResults(v)
	return _u
}

// ClearResults clears the value of the "results" field.
func (_u *BrandKitUpdate) ClearResults() *BrandKitUpdate {
	_u.mutation.ClearResults()
	return _u
}

// SetTrustScore sets the "trust_score" field.
func (_u *BrandKitUpdate) SetTrustScore(v float64) *BrandKitUpdate {
	_u.mutation.ResetTrustScore()
	_u.mutation.SetTrustScore(v)
	return _u
}

// SetNillableTrustScore sets the "trust_score" field if the given value is not nil.
func (_u *BrandKitUpdate) SetNillableTrustScore(v *float64) *BrandKitUpdate {
	if v != nil {
		_u.SetTrustScore(*v)
	}
	return _u
}

// AddTrustScore adds value to the "trust_score" field.
func (_u *BrandKitUpdate) AddTrustScore(v float64) *BrandKitUpdate {
	_u.mutation.AddTrustScore(v)
	return _u
}

// SetFingerprint sets the "fingerprint" field.
func (_u *BrandKitUpdate) SetFingerprint(v string) *BrandKitUpdate {
	_u.mutation.SetFingerprint(v)
	return _u
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_u *BrandKitUpdate) SetNillableFingerprint(v *string) *BrandKitUpdate {
	if v != nil {
		_u.SetFingerprint(*v)
	}
	return _u
}

// ClearFingerprint clears the value of the "fingerprint" field.
func (_u *BrandKitUpdate) ClearFingerprint() *BrandKitUpdate {
	_u.mutation.ClearFingerprint()
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *BrandKitUpdate) SetOwnerID(id int) *BrandKitUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_u *BrandKitUpdate) SetNillableOwnerID(id *int) *BrandKitUpdate {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *BrandKitUpdate) SetOwner(v *User) *BrandKitUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the BrandKitMutation object of the builder.
func (_u *BrandKitUpdate) Mutation() *BrandKitMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *BrandKitUpdate) ClearOwner() *BrandKitUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BrandKitUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BrandKitUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BrandKitUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BrandKitUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BrandKitUpdate) check() error {
	if v, ok := _u.mutation.Prompt(); ok {
		if err := brandkit.PromptValidator(v); err != nil {
			return &ValidationError{Name: "prompt", err: fmt.Errorf(`ent: validator failed for field "BrandKit.prompt": %w`, err)}
		}
	}
	return nil
}

func (_u *BrandKitUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(brandkit.Table, brandkit.Columns, sqlgraph.NewFieldSpec(brandkit.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(brandkit.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Concept(); ok {
		_spec.SetField(brandkit.FieldConcept, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Results(); ok {
		_spec.SetField(brandkit.FieldResults, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResults(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, brandkit.FieldResults, value)
		})
	}
	if _u.mutation.ResultsCleared() {
		_spec.ClearField(brandkit.FieldResults, field.TypeJSON)
	}
	if value, ok := _u.mutation.TrustScore(); ok {
		_spec.SetField(brandkit.FieldTrustScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTrustScore(); ok {
		_spec.AddField(brandkit.FieldTrustScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Fingerprint(); ok {
		_spec.SetField(brandkit.FieldFingerprint, field.TypeString, value)
	}
	if _u.mutation.FingerprintCleared() {
		_spec.ClearField(brandkit.FieldFingerprint, field.TypeString)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   brandkit.OwnerTable,
			Columns: []string{brandkit.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   brandkit.OwnerTable,
			Columns: []string{brandkit.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{brandkit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BrandKitUpdateOne is the builder for updating a single BrandKit entity.
type BrandKitUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BrandKitMutation
}

// SetPrompt sets the "prompt" field.
func (_u *BrandKitUpdateOne) SetPrompt(v string) *BrandKitUpdateOne {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *BrandKitUpdateOne) SetNillablePrompt(v *string) *BrandKitUpdateOne {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetConcept sets the "concept" field.
func (_u *BrandKitUpdateOne) SetConcept(v model.BrandConcept) *BrandKitUpdateOne {
	_u.mutation.SetConcept(v)
	return _u
}

// SetNillableConcept sets the "concept" field if the given value is not nil.
func (_u *BrandKitUpdateOne) SetNillableConcept(v *model.BrandConcept) *BrandKitUpdateOne {
	if v != nil {
		_u.SetConcept(*v)
	}
	return _u
}

// SetResults sets the "results" field.
func (_u *BrandKitUpdateOne) SetResults(v []model.Availability) *BrandKitUpdateOne {
	_u.mutation.SetResults(v)
	return _u
}

// AppendResults appends value to the "results" field.
func (_u *BrandKitUpdateOne) AppendResults(v []model.Availability) *BrandKitUpdateOne {
	_u.mutation.AppendResults(v)
	return _u
}

// ClearResults clears the value of the "results" field.
func (_u *BrandKitUpdateOne) ClearResults() *BrandKitUpdateOne {
	_u.mutation.ClearResults()
	return _u
}

// SetTrustScore sets the "trust_score" field.
func (_u *BrandKitUpdateOne) SetTrustScore(v float64) *BrandKitUpdateOne {
	_u.mutation.ResetTrustScore()
	_u.mutation.SetTrustScore(v)
	return _u
}

// SetNillableTrustScore sets the "trust_score" field if the given value is not nil.
func (_u *BrandKitUpdateOne) SetNillableTrustScore(v *float64) *BrandKitUpdateOne {
	if v != nil {
		_u.SetTrustScore(*v)
	}
	return _u
}

// AddTrustScore adds value to the "trust_score" field.
func (_u *BrandKitUpdateOne) AddTrustScore(v float64) *BrandKitUpdateOne {
	_u.mutation.AddTrustScore(v)
	return _u
}

// SetFingerprint sets the "fingerprint" field.
func (_u *BrandKitUpdateOne) SetFingerprint(v string) *BrandKitUpdateOne {
	_u.mutation.SetFingerprint(v)
	return _u
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_u *BrandKitUpdateOne) SetNillableFingerprint(v *string) *BrandKitUpdateOne {
	if v != nil {
		_u.SetFingerprint(*v)
	}
	return _u
}

// ClearFingerprint clears the value of the "fingerprint" field.
func (_u *BrandKitUpdateOne) ClearFingerprint() *BrandKitUpdateOne {
	_u.mutation.ClearFingerprint()
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *BrandKitUpdateOne) SetOwnerID(id int) *BrandKitUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_u *BrandKitUpdateOne) SetNillableOwnerID(id *int) *BrandKitUpdateOne {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *BrandKitUpdateOne) SetOwner(v *User) *BrandKitUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the BrandKitMutation object of the builder.
func (_u *BrandKitUpdateOne) Mutation() *BrandKitMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *BrandKitUpdateOne) ClearOwner() *BrandKitUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the BrandKitUpdate builder.
func (_u *BrandKitUpdateOne) Where(ps ...predicate.BrandKit) *BrandKitUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BrandKitUpdateOne) Select(field string, fields ...string) *BrandKitUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BrandKit entity.
func (_u *BrandKitUpdateOne) Save(ctx context.Context) (*BrandKit, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BrandKitUpdateOne) SaveX(ctx context.Context) *BrandKit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BrandKitUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BrandKitUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BrandKitUpdateOne) check() error {
	if v, ok := _u.mutation.Prompt(); ok {
		if err := brandkit.PromptValidator(v); err != nil {
			return &ValidationError{Name: "prompt", err: fmt.Errorf(`ent: validator failed for field "BrandKit.prompt": %w`, err)}
		}
	}
	return nil
}

func (_u *BrandKitUpdateOne) sqlSave(ctx context.Context) (_node *BrandKit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(brandkit.Table, brandkit.Columns, sqlgraph.NewFieldSpec(brandkit.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BrandKit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, brandkit.FieldID)
		for _, f := range fields {
			if !brandkit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != brandkit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(brandkit.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Concept(); ok {
		_spec.SetField(brandkit.FieldConcept, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Results(); ok {
		_spec.SetField(brandkit.FieldResults, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResults(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, brandkit.FieldResults, value)
		})
	}
	if _u.mutation.ResultsCleared() {
		_spec.ClearField(brandkit.FieldResults, field.TypeJSON)
	}
	if value, ok := _u.mutation.TrustScore(); ok {
		_spec.SetField(brandkit.FieldTrustScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTrustScore(); ok {
		_spec.AddField(brandkit.FieldTrustScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Fingerprint(); ok {
		_spec.SetField(brandkit.FieldFingerprint, field.TypeString, value)
	}
	if _u.mutation.FingerprintCleared() {
		_spec.ClearField(brandkit.FieldFingerprint, field.TypeString)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   brandkit.OwnerTable,
			Columns: []string{brandkit.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   brandkit.OwnerTable,
			Columns: []string{brandkit.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BrandKit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{brandkit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
