// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/trnahnh/katana-id/internal/db/ent/brandkit"
	"github.com/trnahnh/katana-id/internal/db/ent/predicate"
)

// BrandKitDelete is the builder for deleting a BrandKit entity.
type BrandKitDelete struct {
	config
	hooks    []Hook
	mutation *BrandKitMutation
}

// Where appends a list predicates to the BrandKitDelete builder.
func (_d *BrandKitDelete) Where(ps ...predicate.BrandKit) *BrandKitDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BrandKitDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BrandKitDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BrandKitDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(brandkit.Table, sqlgraph.NewFieldSpec(brandkit.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BrandKitDeleteOne is the builder for deleting a single BrandKit entity.
type BrandKitDeleteOne struct {
	_d *BrandKitDelete
}

// Where appends a list predicates to the BrandKitDelete builder.
func (_d *BrandKitDeleteOne) Where(ps ...predicate.BrandKit) *BrandKitDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BrandKitDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{brandkit.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BrandKitDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
