// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/trnahnh/katana-id/internal/db/ent/brandkit"
	"github.com/trnahnh/katana-id/internal/db/ent/user"
	"github.com/trnahnh/katana-id/internal/model"
)

// BrandKit is the model entity for the BrandKit schema.
type BrandKit struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Prompt holds the value of the "prompt" field.
	Prompt string `json:"prompt,omitempty"`
	// Concept holds the value of the "concept" field.
	Concept model.BrandConcept `json:"concept,omitempty"`
	// Results holds the value of the "results" field.
	Results []model.Availability `json:"results,omitempty"`
	// TrustScore holds the value of the "trust_score" field.
	TrustScore float64 `json:"trust_score,omitempty"`
	// Fingerprint holds the value of the "fingerprint" field.
	Fingerprint string `json:"fingerprint,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BrandKitQuery when eager-loading is set.
	Edges        BrandKitEdges `json:"edges"`
	user_kits    *int
	selectValues sql.SelectValues
}

// BrandKitEdges holds the relations/edges for other nodes in the graph.
type BrandKitEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BrandKitEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BrandKit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case brandkit.FieldConcept, brandkit.FieldResults:
			values[i] = new([]byte)
		case brandkit.FieldTrustScore:
			values[i] = new(sql.NullFloat64)
		case brandkit.FieldID:
			values[i] = new(sql.NullInt64)
		case brandkit.FieldPrompt, brandkit.FieldFingerprint:
			values[i] = new(sql.NullString)
		case brandkit.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case brandkit.ForeignKeys[0]: // user_kits
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BrandKit fields.
func (_m *BrandKit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case brandkit.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case brandkit.FieldPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt", values[i])
			} else if value.Valid {
				_m.Prompt = value.String
			}
		case brandkit.FieldConcept:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field concept", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Concept); err != nil {
					return fmt.Errorf("unmarshal field concept: %w", err)
				}
			}
		case brandkit.FieldResults:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field results", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Results); err != nil {
					return fmt.Errorf("unmarshal field results: %w", err)
				}
			}
		case brandkit.FieldTrustScore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field trust_score", values[i])
			} else if value.Valid {
				_m.TrustScore = value.Float64
			}
		case brandkit.FieldFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fingerprint", values[i])
			} else if value.Valid {
				_m.Fingerprint = value.String
			}
		case brandkit.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case brandkit.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_kits", value)
			} else if value.Valid {
				_m.user_kits = new(int)
				*_m.user_kits = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BrandKit.
// This includes values selected through modifiers, order, etc.
func (_m *BrandKit) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the BrandKit entity.
func (_m *BrandKit) QueryOwner() *UserQuery {
	return NewBrandKitClient(_m.config).QueryOwner(_m)
}

// Update returns a builder for updating this BrandKit.
// Note that you need to call BrandKit.Unwrap() before calling this method if this BrandKit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BrandKit) Update() *BrandKitUpdateOne {
	return NewBrandKitClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BrandKit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BrandKit) Unwrap() *BrandKit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BrandKit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BrandKit) String() string {
	var builder strings.Builder
	builder.WriteString("BrandKit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("prompt=")
	builder.WriteString(_m.Prompt)
	builder.WriteString(", ")
	builder.WriteString("concept=")
	builder.WriteString(fmt.Sprintf("%v", _m.Concept))
	builder.WriteString(", ")
	builder.WriteString("results=")
	builder.WriteString(fmt.Sprintf("%v", _m.Results))
	builder.WriteString(", ")
	builder.WriteString("trust_score=")
	builder.WriteString(fmt.Sprintf("%v", _m.TrustScore))
	builder.WriteString(", ")
	builder.WriteString("fingerprint=")
	builder.WriteString(_m.Fingerprint)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BrandKits is a parsable slice of BrandKit.
type BrandKits []*BrandKit
