// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/trnahnh/katana-id/internal/db/ent/brandkit"
	"github.com/trnahnh/katana-id/internal/db/ent/user"
	"github.com/trnahnh/katana-id/internal/model"
)

// BrandKitCreate is the builder for creating a BrandKit entity.
type BrandKitCreate struct {
	config
	mutation *BrandKitMutation
	hooks    []Hook
}

// SetPrompt sets the "prompt" field.
func (_c *BrandKitCreate) SetPrompt(v string) *BrandKitCreate {
	_c.mutation.SetPrompt(v)
	return _c
}

// SetConcept sets the "concept" field.
func (_c *BrandKitCreate) SetConcept(v model.BrandConcept) *BrandKitCreate {
	_c.mutation.SetConcept(v)
	return _c
}

// SetResults sets the "results" field.
func (_c *BrandKitCreate) SetResults(v []model.Availability) *BrandKitCreate {
	_c.mutation.SetResults(v)
	return _c
}

// SetTrustScore sets the "trust_score" field.
func (_c *BrandKitCreate) SetTrustScore(v float64) *BrandKitCreate {
	_c.mutation.SetTrustScore(v)
	return _c
}

// SetNillableTrustScore sets the "trust_score" field if the given value is not nil.
func (_c *BrandKitCreate) SetNillableTrustScore(v *float64) *BrandKitCreate {
	if v != nil {
		_c.SetTrustScore(*v)
	}
	return _c
}

// SetFingerprint sets the "fingerprint" field.
func (_c *BrandKitCreate) SetFingerprint(v string) *BrandKitCreate {
	_c.mutation.SetFingerprint(v)
	return _c
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_c *BrandKitCreate) SetNillableFingerprint(v *string) *BrandKitCreate {
	if v != nil {
		_c.SetFingerprint(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BrandKitCreate) SetCreatedAt(v time.Time) *BrandKitCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BrandKitCreate) SetNillableCreatedAt(v *time.Time) *BrandKitCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *BrandKitCreate) SetOwnerID(id int) *BrandKitCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_c *BrandKitCreate) SetNillableOwnerID(id *int) *BrandKitCreate {
	if id != nil {
		_c = _c.SetOwnerID(*id)
	}
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *BrandKitCreate) SetOwner(v *User) *BrandKitCreate {
	return _c.SetOwnerID(v.ID)
}

// Mutation returns the BrandKitMutation object of the builder.
func (_c *BrandKitCreate) Mutation() *BrandKitMutation {
	return _c.mutation
}

// Save creates the BrandKit in the database.
func (_c *BrandKitCreate) Save(ctx context.Context) (*BrandKit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BrandKitCreate) SaveX(ctx context.Context) *BrandKit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BrandKitCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BrandKitCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BrandKitCreate) defaults() {
	if _, ok := _c.mutation.TrustScore(); !ok {
		v := brandkit.DefaultTrustScore
		_c.mutation.SetTrustScore(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := brandkit.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BrandKitCreate) check() error {
	if _, ok := _c.mutation.Prompt(); !ok {
		return &ValidationError{Name: "prompt", err: errors.New(`ent: missing required field "BrandKit.prompt"`)}
	}
	if v, ok := _c.mutation.Prompt(); ok {
		if err := brandkit.PromptValidator(v); err != nil {
			return &ValidationError{Name: "prompt", err: fmt.Errorf(`ent: validator failed for field "BrandKit.prompt": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Concept(); !ok {
		return &ValidationError{Name: "concept", err: errors.New(`ent: missing required field "BrandKit.concept"`)}
	}
	if _, ok := _c.mutation.TrustScore(); !ok {
		return &ValidationError{Name: "trust_score", err: errors.New(`ent: missing required field "BrandKit.trust_score"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BrandKit.created_at"`)}
	}
	return nil
}

func (_c *BrandKitCreate) sqlSave(ctx context.Context) (*BrandKit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BrandKitCreate) createSpec() (*BrandKit, *sqlgraph.CreateSpec) {
	var (
		_node = &BrandKit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(brandkit.Table, sqlgraph.NewFieldSpec(brandkit.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Prompt(); ok {
		_spec.SetField(brandkit.FieldPrompt, field.TypeString, value)
		_node.Prompt = value
	}
	if value, ok := _c.mutation.Concept(); ok {
		_spec.SetField(brandkit.FieldConcept, field.TypeJSON, value)
		_node.Concept = value
	}
	if value, ok := _c.mutation.Results(); ok {
		_spec.SetField(brandkit.FieldResults, field.TypeJSON, value)
		_node.Results = value
	}
	if value, ok := _c.mutation.TrustScore(); ok {
		_spec.SetField(brandkit.FieldTrustScore, field.TypeFloat64, value)
		_node.TrustScore = value
	}
	if value, ok := _c.mutation.Fingerprint(); ok {
		_spec.SetField(brandkit.FieldFingerprint, field.TypeString, value)
		_node.Fingerprint = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(brandkit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   brandkit.OwnerTable,
			Columns: []string{brandkit.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_kits = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BrandKitCreateBulk is the builder for creating many BrandKit entities in bulk.
type BrandKitCreateBulk struct {
	config
	err      error
	builders []*BrandKitCreate
}

// Save creates the BrandKit entities in the database.
func (_c *BrandKitCreateBulk) Save(ctx context.Context) ([]*BrandKit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BrandKit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BrandKitMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BrandKitCreateBulk) SaveX(ctx context.Context) []*BrandKit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BrandKitCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BrandKitCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
