// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/trnahnh/katana-id/internal/db/ent/otp"
	"github.com/trnahnh/katana-id/internal/db/ent/predicate"
)

// OTPUpdate is the builder for updating OTP entities.
type OTPUpdate struct {
	config
	hooks    []Hook
	mutation *OTPMutation
}

// Where appends a list predicates to the OTPUpdate builder.
func (_u *OTPUpdate) Where(ps ...predicate.OTP) *OTPUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *OTPUpdate) SetEmail(v string) *OTPUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *OTPUpdate) SetNillableEmail(v *string) *OTPUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *OTPUpdate) SetCode(v string) *OTPUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *OTPUpdate) SetNillableCode(v *string) *OTPUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OTPUpdate) SetExpiresAt(v time.Time) *OTPUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OTPUpdate) SetNillableExpiresAt(v *time.Time) *OTPUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the OTPMutation object of the builder.
func (_u *OTPUpdate) Mutation() *OTPMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OTPUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OTPUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OTPUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OTPUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OTPUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(otp.Table, otp.Columns, sqlgraph.NewFieldSpec(otp.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(otp.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(otp.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(otp.FieldExpiresAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{otp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OTPUpdateOne is the builder for updating a single OTP entity.
type OTPUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OTPMutation
}

// SetEmail sets the "email" field.
func (_u *OTPUpdateOne) SetEmail(v string) *OTPUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *OTPUpdateOne) SetNillableEmail(v *string) *OTPUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *OTPUpdateOne) SetCode(v string) *OTPUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *OTPUpdateOne) SetNillableCode(v *string) *OTPUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OTPUpdateOne) SetExpiresAt(v time.Time) *OTPUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OTPUpdateOne) SetNillableExpiresAt(v *time.Time) *OTPUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the OTPMutation object of the builder.
func (_u *OTPUpdateOne) Mutation() *OTPMutation {
	return _u.mutation
}

// Where appends a list predicates to the OTPUpdate builder.
func (_u *OTPUpdateOne) Where(ps ...predicate.OTP) *OTPUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OTPUpdateOne) Select(field string, fields ...string) *OTPUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OTP entity.
func (_u *OTPUpdateOne) Save(ctx context.Context) (*OTP, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OTPUpdateOne) SaveX(ctx context.Context) *OTP {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OTPUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OTPUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OTPUpdateOne) sqlSave(ctx context.Context) (_node *OTP, err error) {
	_spec := sqlgraph.NewUpdateSpec(otp.Table, otp.Columns, sqlgraph.NewFieldSpec(otp.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OTP.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, otp.FieldID)
		for _, f := range fields {
			if !otp.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != otp.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(otp.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(otp.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(otp.FieldExpiresAt, field.TypeTime, value)
	}
	_node = &OTP{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{otp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
