// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/trnahnh/katana-id/internal/db/ent/predicate"
	"github.com/trnahnh/katana-id/internal/db/ent/provider"
	"github.com/trnahnh/katana-id/internal/db/ent/user"
)

// ProviderUpdate is the builder for updating Provider entities.
type ProviderUpdate struct {
	config
	hooks    []Hook
	mutation *ProviderMutation
}

// Where appends a list predicates to the ProviderUpdate builder.
func (_u *ProviderUpdate) Where(ps ...predicate.Provider) *ProviderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProviderName sets the "provider_name" field.
func (_u *ProviderUpdate) SetProviderName(v string) *ProviderUpdate {
	_u.mutation.SetProviderName(v)
	return _u
}

// SetNillableProviderName sets the "provider_name" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableProviderName(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetProviderName(*v)
	}
	return _u
}

// SetProviderAccountID sets the "provider_account_id" field.
func (_u *ProviderUpdate) SetProviderAccountID(v string) *ProviderUpdate {
	_u.mutation.SetProviderAccountID(v)
	return _u
}

// SetNillableProviderAccountID sets the "provider_account_id" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableProviderAccountID(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetProviderAccountID(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ProviderUpdate) SetUserID(id int) *ProviderUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ProviderUpdate) SetUser(v *User) *ProviderUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ProviderMutation object of the builder.
func (_u *ProviderUpdate) Mutation() *ProviderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ProviderUpdate) ClearUser() *ProviderUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProviderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProviderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Provider.user"`)
	}
	return nil
}

func (_u *ProviderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(provider.Table, provider.Columns, sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderName(); ok {
		_spec.SetField(provider.FieldProviderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderAccountID(); ok {
		_spec.SetField(provider.FieldProviderAccountID, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   provider.UserTable,
			Columns: []string{provider.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   provider.UserTable,
			Columns: []string{provider.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{provider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProviderUpdateOne is the builder for updating a single Provider entity.
type ProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProviderMutation
}

// SetProviderName sets the "provider_name" field.
func (_u *ProviderUpdateOne) SetProviderName(v string) *ProviderUpdateOne {
	_u.mutation.SetProviderName(v)
	return _u
}

// SetNillableProviderName sets the "provider_name" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableProviderName(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetProviderName(*v)
	}
	return _u
}

// SetProviderAccountID sets the "provider_account_id" field.
func (_u *ProviderUpdateOne) SetProviderAccountID(v string) *ProviderUpdateOne {
	_u.mutation.SetProviderAccountID(v)
	return _u
}

// SetNillableProviderAccountID sets the "provider_account_id" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableProviderAccountID(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetProviderAccountID(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ProviderUpdateOne) SetUserID(id int) *ProviderUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ProviderUpdateOne) SetUser(v *User) *ProviderUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ProviderMutation object of the builder.
func (_u *ProviderUpdateOne) Mutation() *ProviderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ProviderUpdateOne) ClearUser() *ProviderUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the ProviderUpdate builder.
func (_u *ProviderUpdateOne) Where(ps ...predicate.Provider) *ProviderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProviderUpdateOne) Select(field string, fields ...string) *ProviderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Provider entity.
func (_u *ProviderUpdateOne) Save(ctx context.Context) (*Provider, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderUpdateOne) SaveX(ctx context.Context) *Provider {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Provider.user"`)
	}
	return nil
}

func (_u *ProviderUpdateOne) sqlSave(ctx context.Context) (_node *Provider, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(provider.Table, provider.Columns, sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Provider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, provider.FieldID)
		for _, f := range fields {
			if !provider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != provider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderName(); ok {
		_spec.SetField(provider.FieldProviderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderAccountID(); ok {
		_spec.SetField(provider.FieldProviderAccountID, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   provider.UserTable,
			Columns: []string{provider.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   provider.UserTable,
			Columns: []string{provider.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Provider{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{provider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
