// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/trnahnh/katana-id/internal/db/ent/brandkit"
	"github.com/trnahnh/katana-id/internal/db/ent/otp"
	"github.com/trnahnh/katana-id/internal/db/ent/provider"
	"github.com/trnahnh/katana-id/internal/db/ent/schema"
	"github.com/trnahnh/katana-id/internal/db/ent/session"
	"github.com/trnahnh/katana-id/internal/db/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	brandkitFields := schema.BrandKit{}.Fields()
	_ = brandkitFields
	// brandkitDescPrompt is the schema descriptor for prompt field.
	brandkitDescPrompt := brandkitFields[0].Descriptor()
	// brandkit.PromptValidator is a validator for the "prompt" field. It is called by the builders before save.
	brandkit.PromptValidator = brandkitDescPrompt.Validators[0].(func(string) error)
	// brandkitDescTrustScore is the schema descriptor for trust_score field.
	brandkitDescTrustScore := brandkitFields[3].Descriptor()
	// brandkit.DefaultTrustScore holds the default value on creation for the trust_score field.
	brandkit.DefaultTrustScore = brandkitDescTrustScore.Default.(float64)
	// brandkitDescCreatedAt is the schema descriptor for created_at field.
	brandkitDescCreatedAt := brandkitFields[5].Descriptor()
	// brandkit.DefaultCreatedAt holds the default value on creation for the created_at field.
	brandkit.DefaultCreatedAt = brandkitDescCreatedAt.Default.(func() time.Time)
	otpFields := schema.OTP{}.Fields()
	_ = otpFields
	// otpDescCreatedAt is the schema descriptor for created_at field.
	otpDescCreatedAt := otpFields[3].Descriptor()
	// otp.DefaultCreatedAt holds the default value on creation for the created_at field.
	otp.DefaultCreatedAt = otpDescCreatedAt.Default.(func() time.Time)
	providerFields := schema.Provider{}.Fields()
	_ = providerFields
	// providerDescCreatedAt is the schema descriptor for created_at field.
	providerDescCreatedAt := providerFields[2].Descriptor()
	// provider.DefaultCreatedAt holds the default value on creation for the created_at field.
	provider.DefaultCreatedAt = providerDescCreatedAt.Default.(func() time.Time)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescToken is the schema descriptor for token field.
	sessionDescToken := sessionFields[0].Descriptor()
	// session.DefaultToken holds the default value on creation for the token field.
	session.DefaultToken = sessionDescToken.Default.(func() string)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[3].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[2].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}
